#Enable/Disable Server Entries overrides
enabled = true
#Internal Version Number. NO TOUCHY!
version = 2
#Server override entries
[[entry]]
    ip = "nameless.thecatrix.ru"
    description = "Играет в Minecraft %mcver%"
    state = "На Nameless (%players%/%maxplayers% игроков)"
    largeImageKey = ["https://raw.githubusercontent.com/TheCatRiX/Nameless/main/nameless.png"]
    largeImageText = "Nameless 2.1.4"
    smallImageKey = ["%playerhead%"]
    smallImageText = "%player%"

[[entry]]
    ip = "45.93.200.211"
    description = "Играет в Minecraft %mcver%"
    state = "На Nameless (%players%/%maxplayers% игроков)"
    largeImageKey = ["https://raw.githubusercontent.com/TheCatRiX/Nameless/main/nameless.png"]
    largeImageText = "Nameless 2.1.4"
    smallImageKey = ["%playerhead%"]
    smallImageText = "%player%"

