name = "Nameless"
author = "CatRiX"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57b797b2d5bc0942ff1827643facc72a348ae6edb938c1a902e1803320566236"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3"]
