name = "Nameless"
author = "CatRiX"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "670ee27977e32c5ba10fb6619e977805272ab504eb99f2b43307e1b5016af67c"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3"]
