name = "Nameless"
author = "CatRiX"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e6c3218ccba39c4293e16545a6c042dbd7c35cdb6557d284d150cb756a695f5"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
