name = "Nameless"
author = "CatRiX"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79ca9b64b709fec0489e20e828178545a3bc9d2e9b8cb4a647c3fb499b7eff13"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
