name = "Nameless"
author = "CatRiX"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cc4f431b17432c9319b80a2c6a8ae09793bceabc0a15ba472bb3e66f6afc229"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
