
[general]
	#Enable/Disable ReplayMod Support
	enabled = true
	#Internal Version Number. NO TOUCHY!
	version = 1

#The Replay Browser Event
[replay_viewer]
	#Enable/Disable the ReplayMod Replay Viewer Event
	enabled = true
	#The first line of text under the app name
	description = "Играет в Minecraft %mcver%"
	#The second line of text under the app name
	state = "В меню повторов"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%replaymod%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%modpack%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%avatar%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player%"
	#The buttons to display on Discord
	buttons = []

#The Replay Editor Event
[replay_editor]
	#Enable/Disable the ReplayMod Editor Event
	enabled = true
	#The first line of text under the app name
	description = "Играет в Minecraft %mcver%"
	#The second line of text under the app name
	state = "Просмотр повтора"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%replaymod%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%modpack%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%avatar%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player%"
	#The buttons to display on Discord
	buttons = []

#The Replay Rendering Event
[replay_render]
	#Enable/Disable the ReplayMod Rendering Event
	enabled = true
	#The first line of text under the app name
	description = "Играет в Minecraft %mcver%"
	#The second line of text under the app name
	state = "Рендер видео (%framecount%)"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%replaymod%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%modpack%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%avatar%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player%"
	#The buttons to display on Discord
	buttons = []

